#/
# @license Apache-2.0
#
# Copyright (c) 2023 The Stdlib Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#/

name: 🚀 Application
description: I'd like to apply to Google Summer of Code to work on stdlib!
title: "[RFC]: "
labels: ["rfc", "2023"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to complete this application!

        A few general notes:

        1.  To be considered, a GSoC application **must** have a written proposal submitted to <https://summerofcode.withgoogle.com/>. The purpose of creating this issue is to allow stdlib mentors to provide feedback and answer any questions you have regarding your prospective project proposal. Note, however, that we will **not** write your proposal for you. You, and you alone, are responsible for writing, and the timely submission of, your project proposal.

        1.  Please use a succinct name to describe your proposal. This issue should use the following issue naming convention:

            -   RFC: the succinct name describing your proposal

            For example,

            -   RFC: improve tiling algorithms for element-wise ndarray iteration
            -   RFC: build a developer dashboard for tracking repository build status

        1.  In your proposal, you should include the following information, as described below.

  - type: markdown
    attributes:
      value: |
        * * *
        ## You the person

        We'd like to get to know you and your background!

  - type: input
    id: full_name
    attributes:
      label: Full name
      description: What is your full name?
      placeholder: e.g., Jane Doe
    validations:
      required: true

  - type: dropdown
    id: enrollment
    attributes:
      label: University status
      description: Are you currently enrolled at a university?
      options:
        - "Yes"
        - "No"
    validations:
      required: true

  - type: input
    id: university
    attributes:
      label: University name
      description: If you are enrolled at a university, what is the name of that university?
    validations:
      required: false

  - type: textarea
    id: bio
    attributes:
      label: Short biography
      description: Please provide a brief overview of your background, including any education/professional qualifications (e.g., university degrees, certificates, etc), technical competencies (e.g., C/C++, JavaScript, CI/CD), and general interests (e.g., high-performance numerical computing, machine learning, frontend development).
    validations:
      required: true

  - type: input
    id: contact
    attributes:
      label: Contact details
      description: How can we contact you? This may include an e-mail address, GitHub username, or other handle. If you have multiple handles/usernames, please list all handles and usernames that you want us to know about in order to help us associate your various usernames with you. Separate each entry with a comma.
      placeholder: email:jane@doe.com,github:janedoe123
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        * * *

        ## You the programmer

        Help us understand your programming experience! Don't worry if you have never used stdlib or Git. Many contributors start fresh, and we'll help teach you what you need to know. :smile:

  - type: dropdown
    id: tech_platform
    attributes:
      label: Platform
      description: What platform do you use to code?
      options:
        - Mac
        - Linux
        - Windows
        - Other
    validations:
      required: true

  - type: textarea
    id: tech_editor
    attributes:
      label: Editor
      description: What is your preferred code editor (e.g., VSCode, Sublime Text, Vim, Emacs, etc) and why?
    validations:
      required: true

  - type: textarea
    id: tech_experience
    attributes:
      label: Programming experience
      description: What is your experience programming? Tell us about something that you've created!
    validations:
      required: true

  - type: textarea
    id: tech_javascript
    attributes:
      label: JavaScript experience
      description: What is your experience with JavaScript? What is your favorite feature of JavaScript? What is your least favorite feature of JavaScript?
    validations:
      required: true

  - type: textarea
    id: tech_nodejs
    attributes:
      label: Node.js experience
      description: What is your experience with Node.js?
    validations:
      required: true

  - type: textarea
    id: tech_native
    attributes:
      label: C/Fortran experience
      description: What is your experience with C and/or Fortran?
    validations:
      required: true

  - type: textarea
    id: tech_stdlib
    attributes:
      label: Interest in stdlib
      description: What interests you about stdlib? Do you have a favorite feature or example? If so, tell us more!
    validations:
      required: true

  - type: dropdown
    id: tech_git
    attributes:
      label: Version control
      description: Have you ever used Git for version control?
      options:
        - "Yes"
        - "No"
    validations:
      required: true

  - type: textarea
    id: tech_stdlib_contributions
    attributes:
      label: Contributions to stdlib
      description: Please provide a brief summary of your contributions to stdlib thus far, including any unmerged work. This should be a list of pull requests and an indication as to whether each pull request is merged, closed, or still open. If you made significant contributions outside of your pull requests (e.g., reviewing someone else's pull request), you may list that as well.
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        * * *

        ## You and your project

        Tell us about your proposal!

        When detailing the project schedule, you are advised to note where along the way where you could formulate a pull request. Ideally, pull requests should be points where you can have self-contained, well-documented, and tested pieces of functionality. Breaking the project into smaller sub-tasks which can be completed as part of one or more pull requests helps to keep branch merges and code reviews reasonable. A large code dump at the end of the program will likely be hard to review and merge before the project deadline.

        Please do **not** copy verbatim text from the list of project ideas or from other people's discussions about your project. Always write your proposal in your own words.

        If you include any significant text or code from another source in your application, you must properly cite the included material. All papers or references that you use or plan to use must be cited. Place all citations in a "References" section at the bottom of each appliable application section. Copying text without citation is plagarism and will result in your application being rejected.

  - type: textarea
    id: proposal_goals
    attributes:
      label: Goals
      description: What do you hope to achieve?
    validations:
      required: true

  - type: textarea
    id: proposal_why
    attributes:
      label: Why this project?
      description: What excites you about the proposed project and why?
    validations:
      required: true

  - type: textarea
    id: proposal_qualifications
    attributes:
      label: Qualifications
      description: What qualifications do you have to execute on your proposal? How are you suited to work on this project? For example, if you are interested in implementing statistical hypothesis tests, what courses have you taken or books have you read on statistics?
    validations:
      required: true

  - type: textarea
    id: proposal_prior_art
    attributes:
      label: Prior art
      description: "How have other people achieved the aims of this project? Has the project been implemented before (e.g., in another programming language or library)? Are there are papers or blog posts about it? (hint: this is likely!)"
    validations:
      required: true

  - type: textarea
    id: proposal_commitment
    attributes:
      label: Commitment
      description: How much time do you plan to invest in the project before, during, and after the Google Summer of Code program? E.g., for part-time contributors, we expect ~20 hr/week during GSoC, but we request that you be explicit in your commitment. If you plan on taking any vacations or time away during the program, let us know about it here.
    validations:
      required: true

  - type: textarea
    id: proposal_schedule
    attributes:
      label: Schedule
      description: Please provide a schedule of how your time will be spent on the subtasks of the project throughout the GSoC program. While this is only preliminary, providing such a schedule will help us monitor your progress throughout the program. Also, during your project, understand that you will issue weekly progress reports against the proposed schedule on your blog.
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        * * *

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please ensure the following tasks are completed before submitting a project proposal.
      options:
        - label: I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
          required: true
        - label: I have read and understood the application materials found in this repository.
          required: true
        - label: I have read and understood the [patch requirement](https://github.com/stdlib-js/google-summary-of-code/blob/develop/README.md#patch-requirement) which is necessary for my application to be considered for acceptance.
          required: true
        - label: The issue name begins with `RFC:` and succinctly describes your proposal.
          required: true
        - label: I understand that, in order to apply to be a GSoC contributor, I must submit my final application to <https://summerofcode.withgoogle.com/> **before** the submission deadline.
          required: true
